// Utils
import { normalizeText } from '@utils/mapData';

const sponsor = [
  'JARDIN EXOTICS',
  'PUERTO ANTIOQUIA',
  'TOMRA',
  'WESTFALIA',
  'CARTAMA',
  'FRUTY GREEN',
  'UNIBAN',
  'CFS',
  'MAERSK',
  'Unitec'
];

export const sponsorList = sponsor.map((e) => normalizeText(e));

const notSponsor = [
  'ARAYA & CIA ABOGADOS',
  'GEOCAMPO',
  'TRACTOCENTRO',
  'AGRÍCOLAS EL RUIZ',
  'AGRILINK',
  'AGROEQUIPOS ALPUJARRA',
  'AGROMAQUINAS',
  'AGRONEGOCIOS',
  'AGROPACK',
  'AGROSAVIA',
  'AGROSTORE',
  'AMENDUNI',
  'ARCANGEL MIGUEL',
  'ASM SORT',
  'ATANARE',
  'AUTORIDAD PORTUARIA BAHÍA DE ALGECIRAS',
  'AVO PAK',
  'BANADUANA',
  'BAYER',
  'BRANDT',
  'CALIDRA',
  'CAMPOFERT',
  'CI TALSA',
  'CMA-CGM',
  'COLINAGRO',
  'COLTRÓPICOS',
  'COMFAMA',
  'CORTEVA BIOLOGICALS',
  'CORPOHASS',
  'CRENTO',
  'EUROFERT',
  'EVOAGRO',
  'FRIOPACKING',
  'FRUTAND',
  'GAICA',
  'GIRO',
  'GRAZIANI',
  'GREEN KEEPER',
  'GREENFRUIT',
  'GRUPO CERRO BRAVO',
  'HAPAG LLOYD',
  'HIPERBARIC',
  'IMPORTADORA MONTECARLO',
  'INNOVAK',
  'INVESA',
  'J&S',
  'LA HACIENDA',
  'LABORAGRO HASS',
  'LIQUIDSEAL',
  'LIVENTUS',
  'MAF RODA',
  'MANAGRO',
  'MEDITERRANEAN SHIPPING COMPANY COLOMBIA',
  'METOS COLOMBIA',
  'MEZCLAS INTEGRALES PROGRAMADAS MIP',
  'MICROFERTISA',
  'MIMTECH',
  'MONÓMEROS',
  'MOTOMART',
  'MULTIVAC',
  'NATURAL HARVEST',
  'NATURE GROWN',
  'NBF',
  'NETAFIM',
  'ONE LINE',
  'PAPELSA',
  'PETRODERIVADOS',
  'PHYTOMA',
  'PIERALISI',
  'PLASTICOS OJARA',
  'RAINFOREST',
  'REFRIDCOL',
  'REFRIMARKET',
  'REFRINDUSTRIAL',
  'RESOF',
  'RIO CLARO',
  'SAFER',
  'SMITCO',
  'SMURFITKAPA',
  'SOLUMAT',
  'SQM',
  'SUNFORETS-EUTECH',
  'SYNGENTA-VALAGRO',
  'SYS',
  'UCC',
  'VERDFRUITS',
  'VIVERO GENESIS',
  'XUCLÁ',
  'YAK LOGÍSTICA INDUSTRIAL',
  'RED AGRÍCOLA',
];

export const notSponsorList = notSponsor.map((e) => normalizeText(e));

const media = [
  'Revista Frutas y Hortalizas',
  'Avobook',
  'Diario Frutícola',
  'Portal Frutícola',
  'Fruittoday',
  'Apeajal'
];

export const mediaList = media.map((e) => normalizeText(e));
